services:
  nginx:
    image: ft_nginx:latest
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: ft_nginx
    depends_on:
      - wordpress
    networks:
      - net
    restart: always
    ports:
      - "3000:443"
    develop:
      watch:
        - action: rebuild
          path: ./requirements/nginx

  mariadb:
    image: ft_mariadb:latest
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: ft_mariadb
    volumes:
      - mariadb:/data
      - ./secrets/mysql_password.txt:/run/secrets/mysql_password:ro
    networks:
      - net
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./requirements/mariadb

  wordpress:
    image: ft_wordpress:latest
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: ft_wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/data
      - ./secrets/mysql_password.txt:/run/secrets/mysql_password:ro
      - ./secrets/wordpress_admin_password.txt:/run/secrets/wordpress_admin_password:ro
    networks:
      - net
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./requirements/wordpress

networks:
  net:
    name: inception_net
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

