[project]
name = "cpp01"
version = "1.0.0"

[submit]
files = [
  "ex*/*{c,h}pp",
  "ex*/Makefile",
  "ex*/.gitignore",
  "ex04/compare.sh",
  "ex04/luden.txt",
  ".gitignore"
]

[submit.preprocessor]
enable_gpm = false
function_paths = []

[submit.validation]
norminette = false
